name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install gatorgrade
    - name: Check minimum commits
      run: |
        COMMIT_COUNT=$(git rev-list --count HEAD)
        echo "Found $COMMIT_COUNT commits"
        if [ $COMMIT_COUNT -lt 6 ]; then
          echo "Error: Repository must have at least 6 commits, found $COMMIT_COUNT"
          exit 1
        else
          echo "✓ Commit requirement satisfied ($COMMIT_COUNT commits)"
        fi
    - name: Check with gatorgrade
      run: |
        gatorgrade --config config/gatorgrade.yml